---
title: "RSF tuning"
output: html_notebook
---

```{r}
library(randomForestSRC, quietly=TRUE)
library(prodlim, quietly=TRUE)
library(pec, quietly=TRUE)
library(survival, quietly=TRUE)
library(R.matlab, quietly=TRUE)
```

```{r}
# paths
basePath = "/home/mohamed/Desktop/CooperLab_Research/KNN_Survival/"
#basePath = "/home/mtageld/Desktop/KNN_Survival/"

# data description
sites = c("GBMLGG") #, "BRCA", "KIPAN", "MM")
dtypes = c("Integ") #, "Genes")

# Hyperparameters to try
treeArray = c(50, 100, 500, 1000)
nodeSizeArray = c(1,3,5,7,9)
nSplitArray = c(0,1)
```

```{r}
site = sites[1]
dtype = dtypes[1]

# Reading the matfiles
dpath = paste(basePath, 'Data/SingleCancerDatasets/', site, '/', 
              site, '_', dtype, '_Preprocessed', sep="")
Data = readMat(paste(dpath, '.mat', sep=""))
splitIdxs = readMat(paste(dpath, '_splitIdxs.mat', sep=""))

# Getting the data in needed format
allInfo = data.frame(allData = Data$Integ.X, time = Data$Survival[1,], 
                     status = 1-Data$Censored[1,])

# define result file
resultFile = paste(basePath, 'Results/9_8Oct2017/RSF_', 
                   site, '_', dtype, '.txt', sep="")
```

```{r}

# Go through folds

for (fold in 1:30){

  # Getting split indices
  trainIdxs = splitIdxs$train[fold][[1]][[1]][1,]
  validIdxs = splitIdxs$valid[fold,]
  testIdxs = splitIdxs$test[[fold]][[1]][1,]
  
  # initialize accuracy
  val_c_indices = c()
  test_c_indices = c()
  
  # Go through hyperparams and get Ci
  
  cat("fold | trees nodes Split | Ci_val Ci_test\n")
  cat("--------------------------------------------\n")
  
  for (i in 1:length(treeArray)){
    for (j in 1:length(nodeSizeArray)){
      for (k in 1:length(nSplitArray)){
        
        # training the model
        train.obj <- rfsrc(Surv(time, status) ~ ., allInfo[trainIdxs,], 
                           nsplit = nSplitArray[k], nodesize = nodeSizeArray[j], 
                           ntree = treeArray[i])
        
        # validate
        val_c_index <- cindex(train.obj, formula = Surv(time, status) ~ ., 
                              data=allInfo[validIdxs,])
        val_c_indices <- c(val_c_indices, val_c_index$AppCindex$rfsrc)
        
        # test
        test_c_index  <- cindex(train.obj, formula = Surv(time, status) ~ ., 
                                data=allInfo[testIdxs,])
        test_c_indices <- c(test_c_indices, test_c_index$AppCindex$rfsrc)
        
        cat(fold, "|", treeArray[i], nodeSizeArray[j], nSplitArray[k], "|",
            val_c_index$AppCindex$rfsrc, test_c_index$AppCindex$rfsrc, "\n") 
        
        # clear space      
        rm(train.obj)
        rm(val_c_index)
        rm(test_c_index)
  
      }
    }
  }
}
```

```{r}
resultData = data.frame(maxTest = test_c_indices[which(val_c_indices == max(val_c_indices))])
  
write.table(resultData, file=resultFile)

cat("\nCi_test is stored to: ", resultFile, "\n")
```


```{r}
runRSF = function(fileDir, shuffle) {

  type = "Gene"
  subtype = "OVBRCAUCEC"
  
  dataFile = paste(fileDir, subtype, '_', type, '/X.csv', sep = '')
  survFile = paste(fileDir, subtype, '_', type, '/T.csv', sep = '')
  censorFile = paste(fileDir, subtype, '_', type, '/O.csv', sep = '')
  
  resultValueFile = paste(fileDir, subtype, '_', type, '/shuffle', shuffle, '.max.txt', sep="")
#  resultAllFile = paste(fileDir, subtype, '_', type, '.shuffle', shuffle, '.all.txt', sep="")
  
  allData <- read.csv(dataFile, header = FALSE)
  survData = read.table(survFile, header = FALSE)
  survData = survData - min(survData) + 1
  censorData = read.table(censorFile, header = FALSE)
  
  n = length(survData$V1)
  
  val_c_indices = c()
  test_c_indices = c()
  
  allInfo = data.frame(allData = allData, y = survData, c = censorData)
  allInfo <- allInfo[sample(nrow(allInfo)),]
  
  test_i = floor(n * 0.2)
  validate_i = 2 * test_i
  
#  testData <- allInfo[(0:test_i),]
  
#  validateData <- allInfo[((test_i + 1):validate_i),]
  
#  trainData <- allInfo[((validate_i + 1):n),]

  testData <- allInfo[((n - test_i + 1):n),]
   
  cat(n-test_i+1, n-validate_i+1, n,"\n") 
  validateData <- allInfo[((n - validate_i + 1):(n - test_i)),]
  
  trainData <- allInfo[(0:(n - validate_i)),]
  
  treeArray = c(50, 100, 500, 1000)
  nodeSizeArray = c(1,3,5,7,9)
  nSplitArray = c(0,1)
  
  for (i in 1:length(treeArray)){
    for (j in 1:length(nodeSizeArray)){
      for (k in 1:length(nSplitArray)){
        
        cat(i, j, k,"\n") 
        # training
        train.obj <- rfsrc(Surv(V1, V1.1) ~ . , trainData, nsplit = nSplitArray[k], nodesize = nodeSizeArray[j], ntree = treeArray[i])
        # validate
        val_c_index <- cindex(train.obj, formula = Surv(V1,V1.1) ~ ., data=validateData)
        val_c_indices <- c(val_c_indices, val_c_index$AppCindex$rfsrc)
        
        #cat("validate c index: ", val_c_index$AppCindex$rfsrc)
        
        # test
        test_c_index  <- cindex(train.obj, formula = Surv(V1,V1.1) ~ ., data=testData)
        test_c_indices <- c(test_c_indices, test_c_index$AppCindex$rfsrc)
        
        #cat(", test c index: ", test_c_index$AppCindex$rfsrc, "\n")
        
        rm(train.obj)
        rm(val_c_index)
        rm(test_c_index)
      }
    }
  }
  
  resultData = data.frame(maxTest = test_c_indices[which(val_c_indices == max(val_c_indices))])
  
  resultAllData = data.frame(val_c_indices =  val_c_indices, test_c_indices = test_c_indices)
  
  write.table(resultData, file=resultValueFile)
  #write.table(resultAllData, file=resultAllFile)    
  
  cat("\nmax is stored to: ", resultValueFile, "\n")
  #cat("\nall data is stored to: ", resultAllFile, "\n")
}


```

